// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psoxctvcgseuublclyhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzb3hjdHZjZ3NldXVibGNseWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjQ3MTQsImV4cCI6MjA2MDQwMDcxNH0.n4tg-doYhN76e9GiN5pZKYIKpQXbp_s9RBw3GARkiMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);